// <auto-generated />
using Calendiario.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calendiario.Data.Migrations
{
    [DbContext(typeof(CalendiarioDbContext))]
    partial class CalendiarioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("Calendiario.Modules.Auth.Profile", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("PinHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("pin_hash");

                    b.HasKey("Id");

                    b.ToTable("profile", null, t =>
                        {
                            t.HasCheckConstraint("CK_profile_id", "id = 1");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
